version: '3'

networks:
  app:

volumes:
  mysql.dev.mysql:
  php.dev.app:

services:
  mysql.dev:
    container_name: mysql.dev
    build:
      context: .
      dockerfile: ${DOCKER_FILE_FOLDER}/mysql/Dockerfile
    ports:
      - ${MYSQL_PORT}:3306
    restart: always
    volumes:
      - mysql.dev.mysql:/var/lib/mysql
      - ${LOG_FOLDER}:/var/log/mysql
    working_dir: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVICE_TAGS: ${SERVICE_TAGS}
      SERVICE_NAME: ${SERVICE_NAME}
    networks:
      - app

  php.dev:
    container_name: php.dev
    build:
      context: .
      dockerfile: ${DOCKER_FILE_FOLDER}/php/Dockerfile
      args:
        USER: ${USER_NAME}
        GROUP: ${GROUP_NAME}
        APP_FOLDER: ${APP_FOLDER}
    user: ${USER_NAME}
    expose:
      - "9000"
    restart: always
    volumes:
      - php.dev.app:/app
    depends_on:
      - mysql.dev
    networks:
      - app

  nginx.dev:
    container_name: nginx.dev
    build:
      context: .
      dockerfile: ${DOCKER_FILE_FOLDER}/nginx/Dockerfile
      args:
        USER: ${USER_NAME}
        GROUP: ${GROUP_NAME}
    ports:
      - ${NGINX_PORT}:80
    restart: always
    volumes:
      - php.dev.app:/app
      - ${LOG_FOLDER}:/var/log/nginx/
    depends_on:
      - php.dev
    networks:
      - app